# Site configuration
# 1. Files excluded from Jekyll builds
# 2. Installed Gems
# 3. Gem settings
# 4. Jekyll settings
# 5. Collections
# 6. Jekyll collections settings
# 7. Site settings
# 8. Site navigation

# 1. Files excluded from Jekyll builds
exclude:
- README.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- screenshot.png
- LICENSE
- CNAME
- Gemfile
- Gemfile.lock
- alembic-jekyll-theme.gemspec

# 2. Installed Gems
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji
- jekyll-remote-theme

# 3. Gem settings
paginate: 2 # jekyll-paginate > items per page
paginate_path: blog/page:num # jekyll-paginate > blog page
jekyll-mentions: https://twitter.com # jekyll-mentions > service used when @replying
twitter:
  username: Sujith Abdul Rahim # jekyll-seo-tag > Owners twitter username
author: Sujith Abdul Rahim # jekyll-seo-tag > default author
social: # jekyll-seo-tag > social overrides
  name: Sujith Abdul Rahim # jekyll-seo-tag > real name
  links:  # jekyll-seo-tag > social aliases (sameAs)
    - https://twitter.com/sujithar37
    - https://www.facebook.com/sujithar37
    - https://www.linkedin.com/in/sujithar37
    - https://plus.google.com/+sujithar37
    - https://github.com/sujiar37

# 4. Jekyll settings
sass:
  style: compressed # Style compression
permalink: pretty  # Permalink style (/YYYY/MM/DD/page-name/)
excerpt_separator: <!-- more --> # Marks end of excerpt in posts
timezone: Asia/Kolkota # Timezone for blog posts and alike

# 5. Collections
collections:
  posts:
    title: Posts # Needed for Siteleaf
    output: true
    description: "My thoughts and ideas ~ BeaDevOps" # The post list page content
    feature_text: |
      Welcome to my Site
    feature_image: "https://picsum.photos/2560/600?image=866"

# 6. Jekyll collections settings
defaults:
  -
    values:
      image: "/assets/default-social-image.png" # Default image for sharing

# 7. Site settings
encoding: utf-8 # Make sure the encoding is right
lang: en-GB # Set the site language
title: "BeaDevOps" # Site name or title, also used in jekyll-seo-tag
logo: "/assets/logo.svg" # Site logo, also used in jekyll-seo-tag
description: "Choose a job you love and you'll never have to work a day in your life ~ Confucious" # Site description and default description, also used in jekyll-seo-tag
url: "https://www.beadevops.com" # Site url, also used in jekyll-seo-tag
baseurl: ""
repo: "https://github.com/sujiar37/beadevops"
email: "beadevops@gmail.com"
# disqus: "alembic-1" # Blog post comments, uncomment the option and set the site ID from your Disqus account
avatarurl: "https://s.gravatar.com/avatar/207c2d2be4f2d40fc12f1fbaa26de059?s=80" # Uses avatars for favicons to get multple sites, eg Gravatar, Twitter, GitHub

# 8. Site navigation
navigation_header:
  Home: /
  Elements: /elements/
  Blog: /blog/
  Categories: /categories/
  Search: /search/
  Fork Alembic: https://github.com/sujiar37

navigation_footer:
  Created by Sujith Abdul Rahim: https://www.beadevops.com

social_links: # Appears in sidebar. Set the urls then uncomment and comment out as desired
  Twitter: https://twitter.com/sujithar37
  LinkedIn: https://www.linkedin.com/in/sujithar37
  Google+: https://plus.google.com/+sujithar37
  GitHub: https://github.com/sujiar37
  link: https://www.beadevops.com
  RSS: /feed.xml

sharing_links: # Appear at the bottom of single blog posts, uncomment and comment out as desired. Colours set the button colour
  Twitter: "#0d94e7"
  facebook: "#3B5998"
  Google+: "#DC4E41"
  # Pinterest: "#BD081C"
  LinkedIn: "#0077B5"
  # tumblr: "#36465D"
  # Reddit: "#FF4500"
  # Hacker News: "#ff6600"
  # Designer News: "#2D72D9"
  Email: ""

remote_theme: sujiar37/beadevops
